### ISSUE TITLE
Beginner Feedback

### ISSUE THREAD

**Issue by garrows** [rwaldron/galileo-io#14]
Hey
I just got my blinking light example up and going and wanted to provide some feedback on difficulties I had. 

I first looked at https://github.com/rwaldron/galileo-io which doesnt give me enough information to get started from scratch. 

Then I found this https://learn.sparkfun.com/tutorials/galileo-getting-started-guide/all which was good but doesn't tell me anything about nodebots (obviously).

Then I read this http://bocoup.com/weblog/intel-galileo-javascript-nodejs/ which led to a bit of confusion. The articles had the blinking light GPIO example which was cool but the follow up examples of `new five.Led(13).blink(500);` led me to believe the same LED should be blinking. It didnt.

After a blind stab in the dark, I thought I would put a multimeter to pin 13 and see if it changes and yes it did. The whole 'pin 13 LED standard' isn't there on the Galileo and your examples suggest it is. 

Another problem I had was the examples using `var Galileo = require("galileo");` and `var Galileo = require("galileo-io");` both didn't work for me however the auto detection using plain old require("johnny-five") worked. 

Hopefully this feedback helps. 

Thanks for making this work on the galileo. Exciting stuff.

**Comment by rwaldron** [comment]
I think this has been addressed via several resources.
