### ISSUE TITLE
galileo-io is maxing out the CPU

### ISSUE THREAD

**Issue by adampasz** [rwaldron/galileo-io#18]
### SUMMARY

Simply requiring the galileo-io library consumes 90-100% CPU.  
### STEPS TO REPRODUCE
1. Install the latest version (0.3.10) of galileo-io on a Galileo Gen. 2 with MRAA.
2. Create a file with the following code, and run it as a background process:

```
var Galileo = require("galileo-io");
setInterval(function() {
  console.log('tick');
}, 5000);
```
1. Use `top` to monitor CPU usage, and observe that the CPU for your node process is around 90%.

Note: We are also able to max out the CPU on a Mac running the code above.

**Comment by datdinh181294** [comment]
Everybody help me!
I had a problem when I was installing galileo-io. Can you help me the problem?
![image](https://cloud.githubusercontent.com/assets/17971914/13909000/6580f4ea-ef40-11e5-946c-ca1c752c644b.png)
Thanks all in advance.
